### ISSUE TITLE
Fix interfaccia del weekly scheduler

### ISSUE THREAD

**Issue by angelamiletidev** [Lola-bunny-owo/TimeFlix-Icon2024#30]
L'interfaccia del weekly scheduler è da sistemare, in quanto:

1. Se oggi è giorno X, e pianifico per un giorno Y (con Y < X nella settimana), non pianifica l'evento per la prossima settimana ma lo pianifica nella settimana corrente. È da sistemare, perché deve pianificare dal presente al futuro (non può pianificare per momenti già passati)
2. Lato grafico, andrebbe sistemato un po' in quanto è troppo "bianco" e con le spaziature un po' approssimate.

**Comment by EC2002** [comment]
Aggiustare generi e durata delle nuove raccomandazioni
